version: '3.8'

services:
  python_app:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - app_network

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "sh", "-c", "mysqladmin ping -h localhost -u root -ppassword"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

networks:
  app_network:

volumes:
  mysql_data:
